name: hf_mistral
model_source: hf
seed: 1234

trainer:
  devices: 32
  num_nodes: 1
  max_epochs: -1 # PTL default. In practice, max_steps will be reached first.
  max_steps: 5000 # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10
  val_check_interval: 500 # we do not want val to run during training, hence setting it at a high number
  check_val_every_n_epoch: null
  num_sanity_val_steps: 0
  limit_val_batches: 0.0
  limit_test_batches: 0.0
  gradient_clip_val: 1.0

exp_manager:
  log_local_rank_0_only: True # reduce file system access pressure
  create_tensorboard_logger: True
  explicit_log_dir: null
  exp_dir: null
  name: hf_mistral
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: step
    save_top_k: 1
    mode: max
    save_last: False
    filename: 'hf_mistral_SFT--{step}-{consumed_samples}'
    model_parallel_size: ${multiply:${distributed_strategy.tensor_model_parallel_size}, ${distributed_strategy.pipeline_model_parallel_size}}
    every_n_train_steps: 10
  log_parameter_norm: True # Logs parameter norm across model parallel ranks
  log_gradient_norm: True # Logs gradient norm across model parallel ranks
  enable_recovery_time_instrumentation: False # default to not printing the detailing timing for recovery
  save_xser: True
  load_xser: True
  save_bf16: False
  async_checkpointing: False # default to not use async checkpointing
  resume_from_checkpoint: /home/ubuntu/converted_hf_style_hf_to_nxdt_tp8pp4/ # manually set the checkpoint file to load from. [SFT change 1 required]

distributed_strategy:
  tensor_model_parallel_size: 32
  pipeline_model_parallel_size: 1
  virtual_pipeline_model_parallel_size: 1
  zero1: True
  sequence_parallel: True
  kv_replicator: 4

data:
  micro_batch_size: 1 # limited by GPU memory
  global_batch_size: 64
  packing: True # [SFT] used for appending multiple records in a single record until seq length supported by model, if false uses pad tokens till seq length. True increases throughput
  use_sft_style_data_module: True # [SFT/PT] used when we want to set the HF style dataloader for megatron model code.
  train_dir: /home/ubuntu/examples_datasets/mistral_7b/training.jsonl # [SFT] '/ubuntu/training.jsonl' or arrow file. As for SFT we use HF style dataloader, we also use HF style data file paths [SFT change 2 required]
  val_dir: /home/ubuntu/examples_datasets/mistral_7b/validation.jsonl # [SFT] '/ubuntu/training.jsonl' or arrow file [SFT change 3 required]
  dev_choose_samples: 2250 # [SFT] if set, will use those many number of records from the head of the dataset instead of using all. Set to null to use full dataset [SFT change 4 required]
  seq_length: 4096 # [SFT change 5 required]
  tokenizer:
    type: /home/ubuntu/mistral_tokenizer # [SFT change 6 required]

model:
  # specify micro_batch_size, global_batch_size, and model parallelism
  # gradient accumulation will be done automatically based on data_parallel_size
  # micro_batch_size: 4 # limited by GPU memory
  # global_batch_size: 8 # will use more micro batches to reach global batch size

  # model architecture
  model_config: /home/ubuntu/Mistral-7B-v0.1/config.json # TODO: Expand this into arguments in this file [SFT change 7 required]
  encoder_seq_length: 32768
  max_position_embeddings: 32768
  num_layers: 32
  hidden_size: 4096
  qkv_linear: True
  rope_theta: 10000.0
  
  # Miscellaneous
  use_cpu_initialization: True # Init weights on the CPU (slow for large models) 
  weight_init_only: True # [SFT] Load only model states and ignore the optim states from ckpt directory

  ## Activation Checkpointing
  activations_checkpoint_granularity: selective # 'selective' or 'full'

  fusions:
    softmax: True
    flash_attention: True
  
  do_layer_norm_weight_decay: True

  optim:
    name: adamw_fp32OptState
    lr: 1.5e-4
    weight_decay: 0.01
    capturable: False
    betas:
    - 0.9
    - 0.999
    sched:
      name: LinearAnnealingWithWarmUp
      warmup_steps: 10
      max_steps: ${trainer.max_steps}

precision:
  type: 'mixed_precision' # ['bf16SR', 'fp32', 'autocast', 'mixed_precision', 'mixed_precisionSR', 'manual']
  # Set the following only if precision type is manual, otherwise they will be automatically set.
  master_weights: False    
  fp32_grad_acc: False
  xla_use_bf16: '0'
  xla_downcast_bf16: '0'
  neuron_rt_stochastic_rounding_en: '0'

compiler_flags: '--model-type transformer --distribution-strategy=llm-training'
compiler_cache_url: /home/ubuntu/neuron_cache
aync_exec_max_inflight_requests: 5
bucket_size_collectives: 1024
neuron_rt_exec_timeout: 100
neuron_experimental_compress_rg: False